export const CREATE_ORDER_REQUEST='CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS='CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL='CREATE_ORDER_FAIL'

export const MY_ORDER_REQUEST='MY_ORDER_REQUEST'
export const MY_ORDER_SUCCESS='MY_ORDER_SUCCESS'
export const MY_ORDER_FAIL='MY_ORDER_FAIL'

export const DETAILS_ORDER_REQUEST='DETAILS_ORDER_REQUEST'
export const DETAILS_ORDER_SUCCESS='DETAILS_ORDER_SUCCESS'
export const DETAILS_ORDER_FAIL='DETAILS_ORDER_FAIL'

export const ORDER_ORDER_REQUEST='ORDER_ORDER_REQUEST'
export const ORDER_ORDER_SUCCESS='ORDER_ORDER_SUCCESS'
export const ORDER_ORDER_FAIL='ORDER_ORDER_FAIL'
export const ORDER_ORDER_RESET='ORDER_ORDER_RESET'

export const UPDATE_ORDER_REQUEST='UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS='UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAIL='UPDATE_ORDER_FAIL'
export const UPDATE_ORDER_RESET='UPDATE_ORDER_RESET'

export const DELETE_ORDER_REQUEST='DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS='DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAIL='DELETE_ORDER_FAIL'
export const DELETE_ORDER_RESET='DELETE_ORDER_RESET'

export const CLEAR_ERRORS='CLEAR'