export const LOGIN_USER_REQUEST='LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL'

export const SIGNUP_USER_REQUEST='SIGNUP_USER_REQUEST'
export const SIGNUP_USER_SUCCESS='SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_FAIL='SIGNUP_USER_FAIL'

export const LOAD_USER_REQUEST='LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS='LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL='LOAD_USER_FAIL'

export const PROFILE_UPDATE_REQUEST='PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS='PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL='PROFILE_UPDATE_FAIL'
export const PROFILE_UPDATE_RESET='PROFILE_UPDATE_RESET'

export const PASSWORD_UPDATE_REQUEST='PASSWORD_UPDATE_REQUEST'
export const PASSWORD_UPDATE_SUCCESS='PASSWORD_UPDATE_SUCCESS'
export const PASSWORD_UPDATE_FAIL='PASSWORD_UPDATE_FAIL'
export const PASSWORD_UPDATE_RESET='PASSWORD_UPDATE_RESET'

export const PASSWORD_FORGOT_REQUEST='PASSWORD_FORGOT_REQUEST'
export const PASSWORD_FORGOT_SUCCESS='PASSWORD_FORGOT_SUCCESS'
export const PASSWORD_FORGOT_FAIL='PASSWORD_FORGOT_FAIL'

export const PASSWORD_RESET_REQUEST='PASSWORD_RESET_REQUEST'
export const PASSWORD_RESET_SUCCESS='PASSWORD_RESET_SUCCESS'
export const PASSWORD_RESET_FAIL='PASSWORD_RESET_FAIL'

export const LOG_OUT_SUCCESS='LOG_OUT_SUCCESS'
export const LOG_OUT_FAIL='LOG_OUT_FAIL'

//BY ADMIN
export const ALL_USER_REQUEST='ALL_USER_REQUEST'
export const ALL_USER_SUCCESS='ALL_USER_SUCCESS'
export const ALL_USER_FAIL='ALL_USER_FAIL'
export const USERS_DETAILS_REQUEST='USERS_DETAILS_REQUEST'
export const USERS_DETAILS_SUCCESS='USERS_DETAILS_SUCCESS'
export const USERS_DETAILS_FAIL='USERS_DETAILS_FAIL'
export const USERS_UPDATE_REQUEST='USERS_UPDATE_REQUEST'
export const USERS_UPDATE_SUCCESS='USERS_UPDATE_SUCCESS'
export const USERS_UPDATE_FAIL='USERS_UPDATE_FAIL'
export const USERS_UPDATE_RESET='USERS_UPDATE_RESET'
export const USERS_DELETE_REQUEST='USERS_DELETE_REQUEST'
export const USERS_DELETE_SUCCESS='USERS_DELETE_SUCCESS'
export const USERS_DELETE_FAIL='USERS_DELETE_FAIL'
export const USERS_DELETE_RESET='USERS_DELETE_RESET'

export const CLEAR_ERRORS='CLEAR'